### ISSUE TITLE
Filter tuning

### ISSUE THREAD

**Issue by semack** [binateq/gps-track-filter#1]
Hi,

First of all, I would say thanks for the great bunch of work you did.
I have a problem, could please advise: 
I have a GPS device which reports it's position every 3 minutes. When a user of it is moving, it seems the filter thinks new positions are the noise and I get just initial position after filtering. 
Could you please advise how to tune the filter to improve this?

Thank you in advance ;)

**Comment by markshevchenko** [comment]
HI.

There are two properties to tune GPS filter: ModelPrecision and
SensorPrecision.

They represent the variance of errors of model and sensor respectively.
You may change these values and check resulting track.

var filter = new GpsTrackFilter();
filter.ModelPrecision = 1.2;
filter.SensorPrecision = 1.4;

You can use the project
https://github.com/binateq/gps-track-filter/tree/master/Binateq.GpsTrackFilter.Demo
from
the solution to produce Geo JSON.
I usually generate
https://github.com/binateq/gps-track-filter/blob/master/Binateq.GpsTrackFilter.Demo/Examples%2BTuples.cs
with
my track and run the *Binateq.GspTrackFilter.Demo.exe* with parameter
*fillocs*.
The program generated Geo JSON wich I can copy-paste to the
http://geojson.io/  site to visual checking.
--
WBR,
  Mark Shevchenko


пт, 27 сент. 2019 г. в 12:23, semack <notifications@github.com>:
